<?php

namespace WH\OrganisationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganisationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganisationTypeRepository extends EntityRepository
{

}
